export const appId = '1:759359119410:web:bca636ad4bed9bf808dc2b';

export const VIEWS = {
  DASHBOARD: 'dashboard',
  VEHICLES: 'vehicles',
  IMPORT: 'import',
  TRANSACTIONS: 'transactions',
  CLOSING: 'closing',
  ALMOXARIFADO: 'almoxarifado',
  RATEIO: 'rateio',
  RELATORIOS: 'relatorios',
  RESUMO: 'resumo',
  ABASTECIMENTO: 'abastecimento',
  RATEIOS: 'rateios'
};

export const FLEET_TYPES = {
  LIGHT: 'Leve',
  HEAVY: 'Pesada'
};

export const VALID_CLASSES = [
  'ANTT',
  'COMBUSTÍVEL',
  'DESPESAS ADMINISTRATIVAS',
  'DESPESAS DE VIAGENS E HOSPEDAGENS',
  'DPVAT (SEGURO OBRIGATORIO)',
  'EMPLACAMENTO DE VEICULO',
  'EPI\'S',
  'EPIS',
  'FERRAMENTAS',
  'FRETES S/ COMPRAS',
  'INSPECAO VEICULAR',
  'LAVAGEM DE FROTAS',
  'LICENCIAMENTO',
  'MANUT. CORRETIVA (FROTA / MAQ)',
  'MANUT. POR ACIDENTE (FROTA / MAQ)',
  'MANUT. PREVENTIVA (FROTA / MAQ)',
  'MANUTENCAO / PECAS E ACES. VEICULOS',
  'MAT. SEGURANCA E PROT. VEICULOS',
  'MATERIAL DE SEGURANCA E PROTECAO',
  'MATERIAL DE USO E CONSUMO',
  'MELHORIA EM FROTAS',
  'MENSALIDADES',
  'MOTO TAXI',
  'OLEO DIESEL',
  'ORDENADOS',
  'PEDAGIO',
  'PNEUS E CAMERAS - NOVOS',
  'PNEUS RESSOLADOS',
  'RAT DESP FINANCEIRAS',
  'REFEICAO E LANCHES',
  'REFORMA DE FROTA',
  'REFORMA DE FROTA (VEICULOS / EQUIP)',
  'SEGUROS',
  'SERVICOS DE PNEUS / BORRACHARIA',
  'SERVICOS DE TERCEIROS',
  'SERVICOS DESPACHANTE POLICIAL',
  'SERVIÇOS DE GUINCHO',
  'TAXA DE COBRANCA',
  'TAXA DE COBRANÇA',
  'TAXAS INMETRO'
];
